server:
  port: 8080

spring:
  application:
    name: spring-batch-pg-mongo

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:  # PostgreSQL (origen de datos de negocio)
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  data:
    mongodb:
      uri: mongodb://localhost:27017/batchdb

batchmeta:  # Solo propiedades personalizadas, no es reconocido automáticamente
  url: jdbc:h2:mem:batchmeta;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  username: sa
  password:
  driver-class-name: org.h2.Driver
